# Generated by Django 4.2.7 on 2023-12-18 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
