# Generated by Django 4.2.7 on 2023-12-18 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
